package lpxie.velocity;

import org.apache.velocity.tools.view.servlet.VelocityLayoutServlet;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Calendar;
import java.util.Date;

/**
 * Created by lpxie on 2017/1/20.
 */
public class MyLayoutServlet extends VelocityLayoutServlet {
    @Override
    protected void doRequest(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        request.setAttribute("Request",request);
        request.setAttribute("ContextPath",request.getContextPath());
        request.setAttribute("BasePath", request.getScheme() + "://" + request.getServerName());

        long runtime = System.currentTimeMillis();
        super.doRequest(request,response);
        if(request.getAttribute("close_comment") == null){
            Date cur_time = Calendar.getInstance(request.getLocale()).getTime();
            PrintWriter pw = response.getWriter();
            pw.print("\r\n<!-- Generated by VelocityApp Server(");
            pw.print(cur_time);
            pw.print(") Cost ");
            pw.print(cur_time.getTime() - runtime);
            pw.print(" ms -->");
            pw.flush();
            pw.close();
        }
    }
}
